### ISSUE TITLE
关于展示的一点问题

### ISSUE THREAD

**Issue by EricTianC** [KikiLetGo/VirusBroadcast#51]
我试图将它截图分享，但每次都找不到合适的时机。
建议增加键盘检测，做出暂停键的效果。
或者增加一个boolean，控制程序在病毒被完全控制（潜伏，感染都为零）时冻结

**Comment by coolleafly** [comment]
只需要简单修改，MyPanel.java。
一个参考，以下代码替换原文line:110 的类，实现特定条件终止。

`
    class MyTimerTask extends TimerTask {
        @Override
        public void run() {
            //动画重绘终止条件， 以被隔离超过100人时停止为例。
            if (PersonPool.getInstance().getPeopleSize(Person.State.FREEZE)<100) {
                MyPanel.this.repaint();
                worldTime++;
            }
        }
    }
`

**Comment by EricTianC** [comment]
感谢，已自行解决 MyPanel.java line:110
`class MyTimerTask extends TimerTask {
        @Override
        public void run() {
            MyPanel.this.repaint();
            if(PersonPool.getInstance().getPeopleSize(Person.State.SHADOW)+PersonPool.getInstance().getPeopleSize(Person.State.CONFIRMED)!=0)
            	worldTime++;
        }
    }`

**Comment by EricTianC** [comment]
感谢，已自行解决 MyPanel.java line:110
`class MyTimerTask extends TimerTask {
        @Override
        public void run() {
            MyPanel.this.repaint();
 if(PersonPool.getInstance().getPeopleSize(Person.State.SHADOW)+PersonPool.getInstance().getPeopleSize(Person.State.CONFIRMED)!=0)
            	worldTime++;
        }
    }`
